Repository CS2103-AY1819S1-F11-1/main, pull requests merged in 2018-10, with the labels that each got.

#49 Update Document
  README.adoc
  docs/UserGuide.adoc
  docs/images/logo.png
Labels: ToReview

#58 Sync command
  src/main/java/seedu/address/logic/commands/SyncCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: ToReview

#82 Correct mistakes based on v1.1 review by TA
  docs/AboutUs.adoc
  src/main/java/seedu/address/model/event/DateTime.java
  src/main/java/seedu/address/model/event/EventName.java
Labels: ToMerge

#73 Remove LO in publish page
  docs/templates/_header.html.slim
Labels: ToMerge

#100 Configure Reposense
  _reposense/config.json
Labels: ToMerge, priority.High

#101 Add Logic: Google Authorization and Get Events - for issue#97, #105, #107
  build.gradle
  src/main/java/seedu/scheduler/logic/commands/GetGoogleCalendarEventsCommand.java
  src/main/java/seedu/scheduler/logic/commands/SyncCommand.java
  src/main/java/seedu/scheduler/logic/parser/SchedulerParser.java
  src/main/resources/credentials/credentials.json
  src/test/java/seedu/scheduler/logic/commands/GetGoogleCalendarEventsCommandTest.java
  src/test/java/seedu/scheduler/logic/parser/SchedulerParserTest.java
Labels: ToReview, priority.High

#113 Update actual UI
  docs/images/Ui.png
Labels: ToReview

#109 Update UserGuide and DeveloperGuide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/EmptyLocalDataBaseDiagram.png
  docs/images/flowChatForDecisionOnLogIn.png
Labels: ToReview

#111 Update DG for Add Command implementation
  docs/DeveloperGuide.adoc
  docs/images/AddCommandActivityDiagram.png
  docs/images/AddCommandSequenceDiagram.png
Labels: ToMerge

#110 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ToReview, priority.Medium

#106 Change Generate Repeat Event to singleton pattern
  src/main/java/seedu/scheduler/logic/RepeatEventGenerator.java
  src/main/java/seedu/scheduler/logic/commands/AddCommand.java
  src/main/java/seedu/scheduler/logic/commands/GetGoogleCalendarEventsCommand.java
  src/main/java/seedu/scheduler/model/event/Event.java
  src/test/java/seedu/scheduler/model/event/EventTest.java
  src/test/java/seedu/scheduler/model/event/RepeatEventGeneratorTest.java
Labels: ToReview

#123 Update DG
  docs/DeveloperGuide.adoc
Labels: priority.High, status.Ongoing

#135 Modularize code
  build.gradle
  src/main/java/seedu/scheduler/MainApp.java
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/logic/commands/GetGoogleCalendarEventsCommand.java
Labels: status.Ongoing

#139 Fix _reposense/config.json and project advisor's photo not showing properly
  _reposense/config.json
  docs/AboutUs.adoc
Labels: ToMerge, ToReview, priority.High

#144 Fix gradle
  build.gradle
Labels: severity.Low

#147 Make-up for v1.2 milestone (DG portion)
  docs/DeveloperGuide.adoc
  docs/diagrams/HistoryCommandAliasActivityDiagram.pptx
  docs/images/HistoryCommandAliasActivityDiagram.png
Labels: ToMerge, ToReview
