Repository CS2103-AY1819S1-F11-1/main, pull requests merged in 2018-11, with the labels that each got.

#152 Add logic for updating popUpManager
  src/main/java/seedu/scheduler/MainApp.java
  src/main/java/seedu/scheduler/logic/commands/AddCommand.java
  src/main/java/seedu/scheduler/model/Model.java
  src/main/java/seedu/scheduler/model/ModelManager.java
  src/main/java/seedu/scheduler/model/PopUpManager.java
  src/main/java/seedu/scheduler/model/event/Event.java
  src/main/java/seedu/scheduler/model/event/EventPopUpInfo.java
  src/main/java/seedu/scheduler/model/event/ReminderDurationList.java
  src/main/java/seedu/scheduler/storage/ReminderDurationListAdapter.java
  src/main/java/seedu/scheduler/ui/EventCard.java
  src/main/resources/view/EventListCard.fxml
  src/test/data/XmlSchedulerStorageTest/invalidAndValidEventScheduler.xml
  src/test/data/XmlSchedulerStorageTest/invalidEventScheduler.xml
  src/test/data/XmlSerializableSchedulerTest/invalidEventScheduler.xml
  src/test/data/XmlSerializableSchedulerTest/typicalEventsScheduler.xml
  src/test/data/XmlUtilTest/invalidEventField.xml
  src/test/data/XmlUtilTest/missingEventField.xml
  src/test/data/XmlUtilTest/validEvent.xml
  src/test/data/XmlUtilTest/validScheduler.xml
  src/test/java/seedu/scheduler/logic/commands/AddCommandTest.java
Labels: ToMerge, ToReview

#156 Implemented auto-completion for commands and their associated aliases
  docs/UserGuide.adoc
  src/main/java/seedu/scheduler/logic/commands/AddTagCommand.java
  src/main/java/seedu/scheduler/ui/CommandBox.java
Labels: ToMerge, ToReview

#159 Update UG: Add info for addTag command
  docs/UserGuide.adoc
Labels: ToMerge, ToReview, documentation

#143 Sync Commands with Google Calendar
  README.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/scheduler/commons/util/EventFormatUtil.java
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/logic/commands/AddCommand.java
  src/main/java/seedu/scheduler/logic/commands/DeleteCommand.java
  src/main/java/seedu/scheduler/logic/commands/EditCommand.java
  src/main/java/seedu/scheduler/logic/commands/GetGoogleCalendarEventsCommand.java
  src/main/java/seedu/scheduler/model/event/Event.java
  src/test/java/seedu/scheduler/logic/commands/EditCommandTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  tokens/StoredCredential
Labels: status.Ongoing

#160 Update link for se-edu team in "About Us"
  docs/AboutUs.adoc
Labels: ToMerge, ToReview, documentation

#165 Add Google Calendar page
  .travis.yml
  build.gradle
  docs/DummySearchPage.html
  docs/UserGuide.adoc
  src/main/java/seedu/scheduler/MainApp.java
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/ui/BrowserPanel.java
  src/main/resources/view/default.html
  src/test/java/seedu/scheduler/ui/BrowserPanelTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/SchedulerSystemTest.java
Labels: ToReview

#163 Fix DeleteCommand: fix implementation for -u
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/logic/commands/DeleteCommand.java
Labels: ToReview

#170 refactor uid to EventUid, refactor uuid to EventSetUid
  docs/DeveloperGuide.adoc
  src/main/java/seedu/scheduler/commons/util/EventFormatUtil.java
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/logic/RepeatEventGenerator.java
  src/main/java/seedu/scheduler/logic/commands/EditCommand.java
  src/main/java/seedu/scheduler/model/ModelManager.java
  src/main/java/seedu/scheduler/model/PopUpManager.java
  src/main/java/seedu/scheduler/model/Scheduler.java
  src/main/java/seedu/scheduler/model/event/Event.java
  src/main/java/seedu/scheduler/model/event/EventPopUpInfo.java
  src/main/java/seedu/scheduler/model/util/SampleSchedulerDataUtil.java
  src/main/java/seedu/scheduler/storage/XmlAdaptedEvent.java
  src/test/data/XmlSchedulerStorageTest/invalidAndValidEventScheduler.xml
  src/test/data/XmlSchedulerStorageTest/invalidEventScheduler.xml
  src/test/data/XmlSerializableSchedulerTest/invalidEventScheduler.xml
  src/test/data/XmlSerializableSchedulerTest/typicalEventsScheduler.xml
  src/test/data/XmlUtilTest/invalidEventField.xml
  src/test/data/XmlUtilTest/missingEventField.xml
  src/test/data/XmlUtilTest/tempScheduler.xml
  src/test/data/XmlUtilTest/validEvent.xml
  src/test/data/XmlUtilTest/validScheduler.xml
  src/test/java/seedu/scheduler/commons/util/XmlUtilTest.java
  src/test/java/seedu/scheduler/logic/commands/EditCommandTest.java
  src/test/java/seedu/scheduler/model/event/EventTest.java
  src/test/java/seedu/scheduler/storage/XmlAdaptedEventTest.java
  src/test/java/seedu/scheduler/testutil/EventBuilder.java
  src/test/java/seedu/scheduler/testutil/TypicalEvents.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.Task

#172 EditCommand: condense code
  src/main/java/seedu/scheduler/commons/util/EventFormatUtil.java
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/logic/commands/EditCommand.java
  src/main/java/seedu/scheduler/model/event/Event.java
Labels: ToMerge, ToReview

#171 Add Test cases
  .gitignore
  src/main/java/seedu/scheduler/logic/commands/AddCommand.java
  src/main/java/seedu/scheduler/logic/parser/AddCommandParser.java
  src/main/java/seedu/scheduler/logic/parser/ParserUtil.java
  src/main/java/seedu/scheduler/model/event/EventList.java
  src/main/java/seedu/scheduler/model/event/exceptions/EventOverflowException.java
  src/main/java/seedu/scheduler/model/util/SampleSchedulerDataUtil.java
  src/test/data/XmlSerializableSchedulerTest/typicalEventsScheduler.xml
  src/test/java/seedu/scheduler/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/scheduler/logic/commands/AddCommandTest.java
  src/test/java/seedu/scheduler/logic/commands/CommandTestUtil.java
  src/test/java/seedu/scheduler/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/scheduler/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/scheduler/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/scheduler/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/scheduler/logic/parser/ParserUtilTest.java
  src/test/java/seedu/scheduler/model/event/EventListTest.java
  src/test/java/seedu/scheduler/model/event/RepeatEventGeneratorTest.java
  src/test/java/seedu/scheduler/testutil/EventBuilder.java
  src/test/java/seedu/scheduler/testutil/TypicalEvents.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: ToReview, week.11

#233 Update PPP and UserGuide
  docs/UserGuide.adoc
  docs/team/chengyuuu.adoc
Labels: ToReview, documentation, week.12

#232 DeveloperGuide.adoc: Update use cases
  docs/DeveloperGuide.adoc
Labels: ToReview, documentation, week.12

#225 RepeatEventGenerator.java: Change repeat logic
  src/main/java/seedu/scheduler/logic/RepeatEventGenerator.java
Labels: ToReview, week.12

#234 Update doc
  docs/team/yezhongz.adoc
Labels: ToMerge, ToReview

#216 Add Tests for add and edit
  src/test/java/seedu/scheduler/logic/commands/CommandTestUtil.java
  src/test/java/seedu/scheduler/testutil/TypicalEvents.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: ToMerge, ToReview, week.11

#230 Fix GetGCEvents
  build.gradle
  src/main/java/seedu/scheduler/commons/util/EventFormatUtil.java
  src/main/java/seedu/scheduler/logic/commands/GetGoogleCalendarEventsCommand.java
Labels: ToMerge, ToReview, type.Bug, week.12

#220 Allow offline mode
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/logic/commands/AddCommand.java
  src/main/java/seedu/scheduler/logic/commands/DeleteCommand.java
  src/main/java/seedu/scheduler/logic/commands/EditCommand.java
  src/main/java/seedu/scheduler/logic/commands/GetGoogleCalendarEventsCommand.java
  src/test/java/seedu/scheduler/logic/commands/GetGoogleCalendarEventsCommandTest.java
  tokens/mode.txt
Labels: ToMerge, ToReview, type.Enhancement, week.12

#228 Refactor Repeat Event Generator
  src/main/java/seedu/scheduler/logic/RepeatEventGenerator.java
  src/main/java/seedu/scheduler/logic/parser/AddCommandParser.java
  src/main/java/seedu/scheduler/model/event/Event.java
  src/test/java/seedu/scheduler/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/scheduler/model/event/RepeatEventGeneratorTest.java
Labels: ToReview, week.12

#239 fix delete single event
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
Labels: severity.High

#226 EditCommand.java: Handle Event DateTime Issues
  src/main/java/seedu/scheduler/logic/commands/EditCommand.java
Labels: ToReview, week.12

#244 fix instance comparison method
  src/main/java/seedu/scheduler/commons/util/EventFormatUtil.java
Labels: ToMerge, ToReview

#252 Enhance offline mode
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/logic/commands/AddCommand.java
  src/main/java/seedu/scheduler/logic/commands/ClearCommand.java
  src/main/java/seedu/scheduler/logic/commands/DeleteCommand.java
  src/main/java/seedu/scheduler/logic/commands/EditCommand.java
  src/main/java/seedu/scheduler/logic/commands/EnterGoogleCalendarModeCommand.java
  src/main/java/seedu/scheduler/logic/parser/SchedulerParser.java
  src/main/java/seedu/scheduler/ui/CommandBox.java
  src/test/java/seedu/scheduler/commons/web/ConnectToGoogleCalendarTest.java
  src/test/java/seedu/scheduler/logic/commands/EnterGoogleCalendarModeCommandTest.java
  src/test/java/seedu/scheduler/logic/parser/SchedulerParserTest.java
  src/test/java/seedu/scheduler/model/event/EventTest.java
Labels: ToMerge, ToReview

#257 Fix the first few instance disappear problem
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
Labels: ToMerge, ToReview

#259 enhance clear command to support google cal
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/logic/commands/AddCommand.java
  src/main/java/seedu/scheduler/logic/commands/ClearCommand.java
  src/main/java/seedu/scheduler/logic/commands/DeleteCommand.java
  src/main/java/seedu/scheduler/logic/commands/EditCommand.java
  src/test/java/seedu/scheduler/commons/web/ConnectToGoogleCalendarTest.java
  tokens/StoredCredential
Labels: ToMerge, ToReview

#263 Add test case, supply credential with write permission
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
  src/test/java/seedu/scheduler/commons/web/ConnectToGoogleCalendarTest.java
  tokens/StoredCredential
Labels: status.Ongoing

#262 final milestone
  .gitignore
  docs/ContactUs.adoc
  docs/UserGuide.adoc
  docs/UsingCheckstyle.adoc
  docs/UsingGradle.adoc
  src/main/java/seedu/scheduler/MainApp.java
  src/main/java/seedu/scheduler/commons/core/LogsCenter.java
  src/main/java/seedu/scheduler/logic/commands/EditCommand.java
  src/main/java/seedu/scheduler/storage/XmlSerializableScheduler.java
  src/main/java/seedu/scheduler/ui/CommandBox.java
  src/main/resources/view/DarkTheme.css
  src/test/data/XmlSchedulerStorageTest/invalidAndValidEventScheduler.xml
  src/test/java/seedu/scheduler/model/VersionedSchedulerTest.java
  src/test/java/seedu/scheduler/model/event/EventNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/scheduler/model/event/EventNameTest.java
  src/test/java/seedu/scheduler/storage/XmlSchedulerStorageTest.java
  src/test/java/seedu/scheduler/testutil/SchedulerBuilder.java
  src/test/java/seedu/scheduler/ui/EventCardTest.java
  src/test/java/seedu/scheduler/ui/EventListPanelTest.java
Labels: documentation, week.12

#267 Fix Event Constructor for eventUid
  src/main/java/seedu/scheduler/logic/RepeatEventGenerator.java
Labels: week.12

#272 Fix ReminderCommands Logic and write test cases
  src/main/java/seedu/scheduler/MainApp.java
  src/main/java/seedu/scheduler/logic/commands/AddReminderCommand.java
  src/main/java/seedu/scheduler/logic/commands/DeleteReminderCommand.java
  src/main/java/seedu/scheduler/logic/commands/PostponeReminderCommand.java
  src/main/java/seedu/scheduler/logic/parser/DeleteReminderCommandParser.java
  src/main/java/seedu/scheduler/logic/parser/ParserUtil.java
  src/main/java/seedu/scheduler/logic/parser/PostponeReminderCommandParser.java
  src/main/java/seedu/scheduler/model/Model.java
  src/main/java/seedu/scheduler/model/ModelManager.java
  src/main/java/seedu/scheduler/model/PopUpManager.java
  src/main/java/seedu/scheduler/model/event/Event.java
  src/main/java/seedu/scheduler/model/event/EventPopUpInfo.java
  src/main/java/seedu/scheduler/model/event/ReminderDurationList.java
  src/main/java/seedu/scheduler/model/event/ReminderTimeList.java
  src/main/java/seedu/scheduler/model/util/SampleSchedulerDataUtil.java
  src/main/java/seedu/scheduler/ui/CommandBox.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/default.html
  src/test/data/XmlSerializableSchedulerTest/typicalEventsScheduler.xml
  src/test/java/seedu/scheduler/logic/commands/AddCommandTest.java
  src/test/java/seedu/scheduler/logic/commands/AddReminderCommandTest.java
  src/test/java/seedu/scheduler/logic/commands/CommandTestUtil.java
  src/test/java/seedu/scheduler/logic/commands/DeleteReminderCommandTest.java
  src/test/java/seedu/scheduler/logic/commands/PostponeReminderCommandTest.java
  src/test/java/seedu/scheduler/logic/parser/AddReminderCommandParserTest.java
  src/test/java/seedu/scheduler/logic/parser/DeleteReminderCommandParserTest.java
  src/test/java/seedu/scheduler/logic/parser/PostponeReminderCommandParserTest.java
  src/test/java/seedu/scheduler/testutil/TypicalEvents.java
  src/test/java/seedu/scheduler/testutil/TypicalIndexes.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: week.12

#265 Add test
  src/main/java/seedu/scheduler/commons/util/EventFormatUtil.java
  src/main/java/seedu/scheduler/commons/web/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/logic/commands/ClearCommand.java
  src/main/java/seedu/scheduler/logic/commands/DeleteCommand.java
  src/main/java/seedu/scheduler/logic/commands/EditCommand.java
  src/main/java/seedu/scheduler/logic/commands/EnterGoogleCalendarModeCommand.java
  src/test/java/seedu/scheduler/commons/web/ConnectToGoogleCalendarTest.java
  src/test/java/seedu/scheduler/logic/commands/CommandTestUtil.java
  src/test/java/seedu/scheduler/logic/commands/EnterGoogleCalendarModeCommandTest.java
  src/test/java/seedu/scheduler/testutil/EventBuilder.java
  src/test/java/seedu/scheduler/testutil/TypicalEvents.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: ToMerge, ToReview, week.12

#270 Change Edit Event Logic
  src/main/java/seedu/scheduler/logic/commands/EditCommand.java
  src/main/java/seedu/scheduler/logic/parser/AddCommandParser.java
  src/main/java/seedu/scheduler/logic/parser/EditCommandParser.java
  src/test/data/XmlSerializableSchedulerTest/typicalEventsScheduler.xml
  src/test/java/seedu/scheduler/logic/commands/CommandTestUtil.java
  src/test/java/seedu/scheduler/logic/commands/EditCommandTest.java
  src/test/java/seedu/scheduler/testutil/EventBuilder.java
  src/test/java/seedu/scheduler/testutil/TypicalEvents.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: ToReview, week.12

#278 Remove clear google test
  src/test/java/seedu/scheduler/commons/web/ConnectToGoogleCalendarTest.java
Labels: ToMerge

#276 refactor EnterGoogleCalendarModeCommand
  src/main/java/seedu/scheduler/commons/util/EventFormatUtil.java
  src/main/java/seedu/scheduler/logic/commands/AddCommand.java
  src/main/java/seedu/scheduler/logic/commands/ClearCommand.java
  src/main/java/seedu/scheduler/logic/commands/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/logic/commands/DeleteCommand.java
  src/main/java/seedu/scheduler/logic/commands/EditCommand.java
  src/main/java/seedu/scheduler/logic/commands/EnterGoogleCalendarModeCommand.java
  src/test/java/seedu/scheduler/logic/commands/ConnectToGoogleCalendarTest.java
Labels: ToMerge, ToReview

#284 Update Ui
  docs/images/Ui.png
Labels: week.12

#286 Refactor ConnectToGoogleCal, FormatUtil
  src/main/java/seedu/scheduler/commons/util/EventFormatUtil.java
  src/main/java/seedu/scheduler/logic/commands/ConnectToGoogleCalendar.java
  src/main/java/seedu/scheduler/logic/commands/EnterGoogleCalendarModeCommand.java
Labels: ToMerge, ToReview, week.13

#288 Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AddCommandActivityDiagram.png
  docs/images/AddCommandSequenceDiagram.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/EditCommandSequenceDiagram2.png
  docs/team/chengyuuu.adoc
Labels: week.13

#287 Some final changes to documentation
  README.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/UsingAppVeyor.adoc
  docs/UsingCheckstyle.adoc
  docs/UsingCoveralls.adoc
  docs/UsingGradle.adoc
  docs/UsingNetlify.adoc
  docs/UsingTravis.adoc
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/images/DeleteEventSdForLogic.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/stylesheets/asciidoctor.css
  docs/team/heartofal1on.adoc
Labels: ToMerge, ToReview, documentation, week.13

#290 DeveloperGuide.adoc: Update Delete implementation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: week.13

#294 Update docu
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/yezhongz.adoc
Labels: week.13
